openapi: 3.0.0
info:
  title: Messages API
  version: 1.0.0
paths:
  /api/v1/messages:
    post:
      summary: List messages with optional filters
      description: Retrieves a list of messages.
      requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  limit:
                    type: integer
                    example: 10
                  page:
                    type: integer
                    example: 1
                  status:
                    type: "string"
                    enum:
                      - "sent"
                      - "read"
                    example: "read"
                required:
                  - limit
      responses:
        '200':
          description: A list of messages
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  messages:
                    type: "array"
                    items:
                      $ref: '#/components/schemas/Message'
                  page:
                    type: integer
                  limit:
                    type: integer
                  totalItems:
                    type: integer
        '422':
          description: Validation error on input
      tags:
        - Messages

  /api/v1//messages/send:
    post:
      summary: Send a new message
      operationId: sendMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  example: "Hello, world!"
      responses:
        '204':
          description: Message sent successfully
        '400':
          description: Error due to missing or invalid parameters
      tags:
        - Messages

components:
  schemas:
    Message:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          description: "Unique identifier for the message"
        text:
          type: string
          description: "Content of the message"
        status:
          type: string
          enum: [read, sent]
          description: "Status of the message"

tags:
  - name: Messages
    description: Operations related to messages